services:
  database:
    image: postgres:latest
    container_name: auth_boilerplate_postgres
    environment:
      - POSTGRES_DB=auth_boilerplate
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
